# 项目端口以及运行模式
server:
  address: 9501
  model: debug # debug/release

# 数据库配置
database:
  dialects: mysql
  host: 127.0.0.1
  port: 3306
  db: cdn
  username: root
  password: root
  charset: utf8
  maxIdle: 50 # 最大空闲
  maxOpen: 150 # 最大连接

# redis配置
redis:
  address: 127.0.0.1:6379
  password:
  db: 0

# 文件上传配置
fileSettings:
  uploadDir: /easy-go-admin/upload/
  host: http://localhost:9501

# log日志配置
log:
  path: ./log
  name: sys
  model: console # console/file

# 远程后台api
admin:
  api: http://154.9.25.140
  apiKey: Rj3eZvEu2gLlSOAd
  apiSecret: NXkcsobduy9DGw7e6YOpU0vlAjLqVJ